### ISSUE TITLE
调用方法报错：ngbatis sessionPool is null

### ISSUE THREAD

**Issue by zhangxk-ocean** [nebula-contrib/ngbatis#157]
加配置了，还是null，这个该怎么解决呢
nebula:
  ngbatis:
    use-session-pool: true

**Comment by zhangxk-ocean** [comment]
那这不换版本的话就无解了呀

**Comment by CorvusYe** [comment]
```yml
nebula:
  ngbatis:
    use-session-pool: false
```
不启用 sessionPool 的特性也会报错吗
