### ISSUE TITLE
数据查询失败：java.net.SocketException: Connection reset

### ISSUE THREAD

**Issue by zhangxs0110** [nebula-contrib/ngbatis#158]
![1684891842410](https://github.com/nebula-contrib/ngbatis/assets/30280161/c14d6415-b083-41d1-847a-03360a025694)
经常出现这个问题，这是什么原因啊

**Comment by CorvusYe** [comment]
关于连接数的配置是怎么样的，可以适当加点最小连接数试试

**Comment by zhangxs0110** [comment]
![image](https://github.com/nebula-contrib/ngbatis/assets/30280161/cb727da4-041e-423e-bdd1-e9817775f583)
越是接口频繁调用时，越容易出现这个问题

**Comment by CorvusYe** [comment]
最小连接是 0 的时候，或频繁获取连接跟释放连接，整体会不稳定一些，
可以修改下这个参数 min-conns-size，我自己是用 2，可以根据项目情况做适当调整，建议大于1

**Comment by zhangxs0110** [comment]
好的，我试试

**Comment by zhangxs0110** [comment]
还是会出现这个错误。
![image](https://github.com/nebula-contrib/ngbatis/assets/30280161/3703e203-4f4a-41bd-8e60-933eda58cf8a)

![image](https://github.com/nebula-contrib/ngbatis/assets/30280161/273d7b05-7ba0-4910-b1e9-083fb35614a5)
![image](https://github.com/nebula-contrib/ngbatis/assets/30280161/076019a4-9f96-4b08-b414-5b787eb36b64)
我感觉和这个LocalSession有关系

**Comment by CorvusYe** [comment]
> ![image](https://github.com/nebula-contrib/ngbatis/assets/30280161/cb727da4-041e-423e-bdd1-e9817775f583)
> 越是接口频繁调用时，越容易出现这个问题

下午我用JMeter试一下，如果是这个情况，那就不是上一条所说的太久没用连接失活的问题

**Comment by CorvusYe** [comment]
## 默认配置
```yml
nebula:
  ngbatis:
    # space name needs to be informed through annotations(@Space) or xml(space="test")
    # default false(false: Session pool map will not be initialized)
    use-session-pool: false
  hosts: 127.0.0.1:19669
  username: root
  password: nebula
  space: test
  pool-config:
    min-conns-size: 0
    max-conns-size: 10
    timeout: 6000
    idle-time: 0
    interval-idle: -1
    wait-time: 6000
    min-cluster-health-rate: 1.0
    enable-ssl: false
```
- 第一次测试（17:54:20)
  - ![image](https://github.com/nebula-contrib/ngbatis/assets/15630211/d6d3c328-9142-4624-9aba-f503c497cd4c)

  - ![image](https://github.com/nebula-contrib/ngbatis/assets/15630211/b916cbb4-2d43-4937-9fa9-77d3e6feb840)
  - ![image](https://github.com/nebula-contrib/ngbatis/assets/15630211/171fa880-f7d2-499b-82ed-478e830a9b33)

  - [5000-435s-result.zip](https://github.com/nebula-contrib/ngbatis/files/11574045/5000-435s-result.zip)

到这里，已经初步可以判断错误的产生不像是高频的访问

- 第二次测试（18:13:19）
    - ![image](https://github.com/nebula-contrib/ngbatis/assets/15630211/01385aad-917f-450d-8c4d-306b1e875222)
    - 报错信息：
        ![image](https://github.com/nebula-contrib/ngbatis/assets/15630211/f9d484c9-6c28-4f2e-b884-2fa5943538db)

> 保持连接过久，从而导致的释放失败，或许才是原因所在。

- 第三次测试（18:25:08）
    - ![image](https://github.com/nebula-contrib/ngbatis/assets/15630211/4f7d2e4b-5a1b-4e4b-bc7e-a748702093ff)

经过小于上次中断时间的等待之后进行的测试三，基本确定在10分钟以内，连接还是健康的，但具体时间不能确定。

## 修改配置，并重启服务器
    ```yml
    nebula:
      ngbatis:
        session-life-length: 300000
        check-fixed-rate: 300000
        # space name needs to be informed through annotations(@Space) or xml(space="test")
        # default false(false: Session pool map will not be initialized)
        use-session-pool: false
      hosts: 127.0.0.1:19669
      username: root
      password: nebula
      space: test
      pool-config:
        min-conns-size: 0
        max-conns-size: 10
        timeout: 6000
        idle-time: 0
        interval-idle: -1
        wait-time: 6000
        min-cluster-health-rate: 1.0
        enable-ssl: false
    ```
- 测试1 (19:29:31)
   - ![image](https://github.com/nebula-contrib/ngbatis/assets/15630211/736686e7-5b05-4c9c-8a0d-38f52dcfae5e)
- 测试2 (20:22:45)
   - ![image](https://github.com/nebula-contrib/ngbatis/assets/15630211/4e24b34c-70de-4dd2-99ce-380d38b7aa66)

![image](https://github.com/nebula-contrib/ngbatis/assets/15630211/9553fafa-d50a-47ed-9869-5be736e9b01d)

这边虽然重连设置的是 5分钟，但因为检查频率是5分钟，开始检查时，距连接创建的时间很接近5分钟，但还没到，所以整体的连接释放时间将近 10 分钟。

可以看出在不启用 sessionPool 的情况下，通过这个配置，并没有发生请求失败的问题，并且可以看到测试2的过程中，又启用了一次重连检查。从而有效维持了连接的健康状态。规避了 失活后不能释放长久占用连接池 的问题。
