### ISSUE TITLE
Error occurred when modifying 'cql. parser. statement start'

### ISSUE THREAD

**Issue by AhYi8** [nebula-contrib/ngbatis#242]
我用的是 1.1.5 版本的

因为是公司内网，所以不能截图，只能描述一下
我在修改
```yml
cql:
  parser:
    statement-start: "<%"
```
此项配置时，报了`Failed to convert from type [java.lang.String] to type [java.lang.Boolean]`
看了一下源码，问题好像出在 `org.nebula.contrib.ngbatis.NgbatisContextInitializer.class` 类的 `readParseCfgProps()` 方法，请作者确认一下，感谢；

还有一个问题，就是你的定界符默认是 `@` 符号，那我插入边的时候的语句里也有 `@` 符号会不会也被当做定界符，该怎么解决？
