### ISSUE TITLE
java.net.SocketException: Socket closed

### ISSUE THREAD

**Issue by zhihangv2** [nebula-contrib/ngbatis#283]
![image](https://github.com/nebula-contrib/ngbatis/assets/153062244/15e9404b-73ef-4e08-a7b3-cfb122416f07)

有时候会报这个错误，是连接池的原因吗？
![image](https://github.com/nebula-contrib/ngbatis/assets/153062244/a222740b-5ef9-4f58-a051-2647af7ce742)

**Comment by CorvusYe** [comment]
可以看下yml文件吗，里面有两个参数：
```yaml
nebula:
  ngbatis:
    session-life-length: 300000
    check-fixed-rate: 300000
```
如果这个值太长，有可能因为连接太久失活而导致无法清理
