### ISSUE TITLE
No extra connection: Timeout waiting for idle object, borrowMaxWaitDuration=PT0S

### ISSUE THREAD

**Issue by hejiahuichengxuyuan** [nebula-contrib/ngbatis#29]
请问这个是在哪里能设置呢？因为我是多线程批量插入的，可能是创建多个session的原因

**Comment by CorvusYe** [comment]
不知道你开了多鞘线程，你可以试试这个：
```
nebula:
  pool-config:
    max-conns-size: 10
```
不够用就多开点。

**Comment by hejiahuichengxuyuan** [comment]
- 我的设置是这样的，但是依然是发生错误
```
pool-config:
    min-conns-size: 0
    max-conns-size: 9999
    timeout: 0
    idle-time: 0
    interval-idle: -1
    wait-time: 0
    min-cluster-health-rate: 1.0
    enable-ssl: false
```
