### ISSUE TITLE
与mybatis的兼容问题

### ISSUE THREAD

**Issue by Szt-1** [nebula-contrib/ngbatis#53]
在同一工程中，引入mybatis-plus管理mysql，并引入ngbatis管理nebula，会发生冲突，工程起不来

**Comment by CorvusYe** [comment]
是否是因为xml都放在了 resources/mapper 下，可以试着把访问nebula的xml存放路径换个目录
```yml
cql:
  parser:
    # 更换开发者自定义的 xml 所在位置
    mapper-locations: ng-mapper/**/*.xml # 默认为 mapper/**/*.xml
```
或者把mybatis的xml换个目录
