### ISSUE TITLE
java.net.SocketException: Connection reset by peer: socket write error

### ISSUE THREAD

**Issue by hejiahuichengxuyuan** [nebula-contrib/ngbatis#81]
```
org.nebula.contrib.ngbatis.exception.QueryException: 数据查询失败：java.net.SocketException: Connection reset by peer: socket write error
```
- 有时会断开连接的情况，请问我应该如何配置？我是根据
```
nebula:
  hosts: 127.0.0.1:19669, ip:port, ....
  username: root
  password: nebula
  space: test
  pool-config:
    min-conns-size: 0
    max-conns-size: 10
    timeout: 0
    idle-time: 0
    interval-idle: -1
    wait-time: 0
    min-cluster-health-rate: 1.0
    enable-ssl: false
```
