### ISSUE TITLE
是否支持打印 SQL日志？

### ISSUE THREAD

**Issue by hejiahuichengxuyuan** [nebula-contrib/ngbatis#9]
你好，我想询问下我已经可以使用了，但是我想打印一下执行的SQL日志，是否有支持此项功能？如果有的话请告知下我谢谢  :D

**Comment by CorvusYe** [comment]
application.yml 里面追加配置就可以了
```yml
logging:
  level:
    org.nebula.contrib: DEBUG
```
